// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: referral_notification.
// - Entity ID: 102019a692c38da74d2b995f0e35b18ad34.
// - Entity Version: 102019a6e88bed67236939f705e5b6af790.
// - Task ID: 69120bf9228d86cc3a65654e.
// - Task Root ID: 6910a741b1b70bd284b566f2.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for ReferralNotificationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ReferralNotificationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  referred_by_user_id: string;
  friend_name: string;
  friend_whatsapp: string;
  notification_sent: boolean;
  sent_at?: string | null;
}

/**
 * ORM class for ReferralNotification entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ReferralNotificationORM {
  private static instance: ReferralNotificationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a692c38da74d2b995f0e35b18ad34';
    this.entityName = 'referral_notification';
    this.entityVersion = '102019a6e88bed67236939f705e5b6af790';
    this.taskId = '69120bf9228d86cc3a65654e';
    this.taskRootId = '6910a741b1b70bd284b566f2';
  }

  /**
   * Get singleton instance of ReferralNotificationORM
   */
  public static getInstance(): ReferralNotificationORM {
    if (!ReferralNotificationORM.instance) {
      ReferralNotificationORM.instance = new ReferralNotificationORM();
    }
    
    return ReferralNotificationORM.instance;
  }

  /**
   * Get all ReferralNotification records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllReferralNotification(): Promise<ReferralNotificationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ReferralNotification record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertReferralNotification(data: ReferralNotificationModel[]): Promise<ReferralNotificationModel[]> {
    const structured = data.map((item) => CreateData(ReferralNotificationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ReferralNotification records
   */
  async purgeAllReferralNotification(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ReferralNotification records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listReferralNotification(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ReferralNotificationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get referral_notification by Id index
   * This function gets data by index.
   */
  async getReferralNotificationById(
    id: string,
  ): Promise<ReferralNotificationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) referral_notification by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setReferralNotificationById(
    id: string,
    data: ReferralNotificationModel
  ): Promise<ReferralNotificationModel[]> {
    const index = createIndexId(
      id
    );

    const values = ReferralNotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete referral_notification by Id index
   */
  async deleteReferralNotificationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get referral_notification by DataCreator index
   * This function gets data by index.
   */
  async getReferralNotificationByDataCreator(
    data_creator: string,
  ): Promise<ReferralNotificationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) referral_notification by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setReferralNotificationByDataCreator(
    data_creator: string,
    data: ReferralNotificationModel
  ): Promise<ReferralNotificationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ReferralNotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete referral_notification by DataCreator index
   */
  async deleteReferralNotificationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get referral_notification by DataUpdater index
   * This function gets data by index.
   */
  async getReferralNotificationByDataUpdater(
    data_updater: string,
  ): Promise<ReferralNotificationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) referral_notification by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setReferralNotificationByDataUpdater(
    data_updater: string,
    data: ReferralNotificationModel
  ): Promise<ReferralNotificationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ReferralNotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete referral_notification by DataUpdater index
   */
  async deleteReferralNotificationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get referral_notification by ReferredByUserId index
   * This function gets data by index.
   */
  async getReferralNotificationByReferredByUserId(
    referred_by_user_id: string,
  ): Promise<ReferralNotificationModel[]> {
    const index = createIndexReferredByUserId(
      referred_by_user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) referral_notification by ReferredByUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setReferralNotificationByReferredByUserId(
    referred_by_user_id: string,
    data: ReferralNotificationModel
  ): Promise<ReferralNotificationModel[]> {
    const index = createIndexReferredByUserId(
      referred_by_user_id
    );

    const values = ReferralNotificationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete referral_notification by ReferredByUserId index
   */
  async deleteReferralNotificationByReferredByUserId(
    referred_by_user_id: string
  ): Promise<void> {
    const index = createIndexReferredByUserId(
      referred_by_user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ReferralNotificationModel data array
   */
  private resultToData(values: Data[]): ReferralNotificationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ReferralNotificationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ReferralNotificationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ReferralNotificationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ReferralNotificationModel => item !== null);
  }
}

/**
 * Convert ReferralNotificationModel data to Value array
 */
function ReferralNotificationModelToValues(data: ReferralNotificationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'referred_by_user_id', type: DataType.string, defaultValue: '' },
    { key: 'friend_name', type: DataType.string, defaultValue: '' },
    { key: 'friend_whatsapp', type: DataType.string, defaultValue: '' },
    { key: 'notification_sent', type: DataType.boolean, defaultValue: false },
    { key: 'sent_at', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ReferralNotificationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ReferralNotificationModel data
 */
function ReferralNotificationModelFromValues(values: Value[]): ReferralNotificationModel {
  const data: Partial<ReferralNotificationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'referred_by_user_id':
        data.referred_by_user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'friend_name':
        data.friend_name = ParseValue(value, DataType.string) as string;
        break;
      case 'friend_whatsapp':
        data.friend_whatsapp = ParseValue(value, DataType.string) as string;
        break;
      case 'notification_sent':
        data.notification_sent = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'sent_at':
        data.sent_at = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as ReferralNotificationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ReferredByUserId fields
 */
function createIndexReferredByUserId(
  referred_by_user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, referred_by_user_id, 'referred_by_user_id'),
  ];

  return {
    fields: ['referred_by_user_id'],
    values
  };
}

export default ReferralNotificationORM;