// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_data.
// - Entity ID: 102019a692c38d97ae29cd4f770c0053e08.
// - Entity Version: 102019a6e88bed67236939f705e5b6af790.
// - Task ID: 69120bf9228d86cc3a65654e.
// - Task Root ID: 6910a741b1b70bd284b566f2.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for UserDataModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserDataModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  full_name: string;
  email: string;
  whatsapp: string;
  city?: string | null;
  state?: string | null;
  referral_friend_name?: string | null;
  referral_friend_whatsapp?: string | null;
}

/**
 * ORM class for UserData entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserDataORM {
  private static instance: UserDataORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a692c38d97ae29cd4f770c0053e08';
    this.entityName = 'user_data';
    this.entityVersion = '102019a6e88bed67236939f705e5b6af790';
    this.taskId = '69120bf9228d86cc3a65654e';
    this.taskRootId = '6910a741b1b70bd284b566f2';
  }

  /**
   * Get singleton instance of UserDataORM
   */
  public static getInstance(): UserDataORM {
    if (!UserDataORM.instance) {
      UserDataORM.instance = new UserDataORM();
    }
    
    return UserDataORM.instance;
  }

  /**
   * Get all UserData records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserData(): Promise<UserDataModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserData record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserData(data: UserDataModel[]): Promise<UserDataModel[]> {
    const structured = data.map((item) => CreateData(UserDataModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserData records
   */
  async purgeAllUserData(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserData records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserData(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserDataModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_data by Id index
   * This function gets data by index.
   */
  async getUserDataById(
    id: string,
  ): Promise<UserDataModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_data by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserDataById(
    id: string,
    data: UserDataModel
  ): Promise<UserDataModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_data by Id index
   */
  async deleteUserDataById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_data by DataCreator index
   * This function gets data by index.
   */
  async getUserDataByDataCreator(
    data_creator: string,
  ): Promise<UserDataModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_data by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserDataByDataCreator(
    data_creator: string,
    data: UserDataModel
  ): Promise<UserDataModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_data by DataCreator index
   */
  async deleteUserDataByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_data by DataUpdater index
   * This function gets data by index.
   */
  async getUserDataByDataUpdater(
    data_updater: string,
  ): Promise<UserDataModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_data by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserDataByDataUpdater(
    data_updater: string,
    data: UserDataModel
  ): Promise<UserDataModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_data by DataUpdater index
   */
  async deleteUserDataByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_data by Email index
   * This function gets data by index.
   */
  async getUserDataByEmail(
    email: string,
  ): Promise<UserDataModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_data by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserDataByEmail(
    email: string,
    data: UserDataModel
  ): Promise<UserDataModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = UserDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_data by Email index
   */
  async deleteUserDataByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_data by Whatsapp index
   * This function gets data by index.
   */
  async getUserDataByWhatsapp(
    whatsapp: string,
  ): Promise<UserDataModel[]> {
    const index = createIndexWhatsapp(
      whatsapp
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_data by Whatsapp index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserDataByWhatsapp(
    whatsapp: string,
    data: UserDataModel
  ): Promise<UserDataModel[]> {
    const index = createIndexWhatsapp(
      whatsapp
    );

    const values = UserDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_data by Whatsapp index
   */
  async deleteUserDataByWhatsapp(
    whatsapp: string
  ): Promise<void> {
    const index = createIndexWhatsapp(
      whatsapp
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserDataModel data array
   */
  private resultToData(values: Data[]): UserDataModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserDataModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserDataModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserDataModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserDataModel => item !== null);
  }
}

/**
 * Convert UserDataModel data to Value array
 */
function UserDataModelToValues(data: UserDataModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'full_name', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'whatsapp', type: DataType.string, defaultValue: '' },
    { key: 'city', type: DataType.string, defaultValue: null },
    { key: 'state', type: DataType.string, defaultValue: null },
    { key: 'referral_friend_name', type: DataType.string, defaultValue: null },
    { key: 'referral_friend_whatsapp', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserDataModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserDataModel data
 */
function UserDataModelFromValues(values: Value[]): UserDataModel {
  const data: Partial<UserDataModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'full_name':
        data.full_name = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'whatsapp':
        data.whatsapp = ParseValue(value, DataType.string) as string;
        break;
      case 'city':
        data.city = ParseValue(value, DataType.string) as string | null;
        break;
      case 'state':
        data.state = ParseValue(value, DataType.string) as string | null;
        break;
      case 'referral_friend_name':
        data.referral_friend_name = ParseValue(value, DataType.string) as string | null;
        break;
      case 'referral_friend_whatsapp':
        data.referral_friend_whatsapp = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as UserDataModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for Whatsapp fields
 */
function createIndexWhatsapp(
  whatsapp: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, whatsapp, 'whatsapp'),
  ];

  return {
    fields: ['whatsapp'],
    values
  };
}

export default UserDataORM;