// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: advertisement.
// - Entity ID: 102019a692c38da700e80e0ae6ae2aae619.
// - Entity Version: 102019a6e88bed67236939f705e5b6af790.
// - Task ID: 69120bf9228d86cc3a65654e.
// - Task Root ID: 6910a741b1b70bd284b566f2.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for AdvertisementModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AdvertisementModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  title: string;
  description?: string | null;
  image_url: string;
  link_url: string;
  position: number;
  is_active: boolean;
  start_date: string;
  end_date?: string | null;
}

/**
 * ORM class for Advertisement entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AdvertisementORM {
  private static instance: AdvertisementORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a692c38da700e80e0ae6ae2aae619';
    this.entityName = 'advertisement';
    this.entityVersion = '102019a6e88bed67236939f705e5b6af790';
    this.taskId = '69120bf9228d86cc3a65654e';
    this.taskRootId = '6910a741b1b70bd284b566f2';
  }

  /**
   * Get singleton instance of AdvertisementORM
   */
  public static getInstance(): AdvertisementORM {
    if (!AdvertisementORM.instance) {
      AdvertisementORM.instance = new AdvertisementORM();
    }
    
    return AdvertisementORM.instance;
  }

  /**
   * Get all Advertisement records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAdvertisement(): Promise<AdvertisementModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Advertisement record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAdvertisement(data: AdvertisementModel[]): Promise<AdvertisementModel[]> {
    const structured = data.map((item) => CreateData(AdvertisementModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Advertisement records
   */
  async purgeAllAdvertisement(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Advertisement records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAdvertisement(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AdvertisementModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get advertisement by Id index
   * This function gets data by index.
   */
  async getAdvertisementById(
    id: string,
  ): Promise<AdvertisementModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) advertisement by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdvertisementById(
    id: string,
    data: AdvertisementModel
  ): Promise<AdvertisementModel[]> {
    const index = createIndexId(
      id
    );

    const values = AdvertisementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete advertisement by Id index
   */
  async deleteAdvertisementById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get advertisement by DataCreator index
   * This function gets data by index.
   */
  async getAdvertisementByDataCreator(
    data_creator: string,
  ): Promise<AdvertisementModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) advertisement by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdvertisementByDataCreator(
    data_creator: string,
    data: AdvertisementModel
  ): Promise<AdvertisementModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AdvertisementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete advertisement by DataCreator index
   */
  async deleteAdvertisementByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get advertisement by DataUpdater index
   * This function gets data by index.
   */
  async getAdvertisementByDataUpdater(
    data_updater: string,
  ): Promise<AdvertisementModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) advertisement by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdvertisementByDataUpdater(
    data_updater: string,
    data: AdvertisementModel
  ): Promise<AdvertisementModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AdvertisementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete advertisement by DataUpdater index
   */
  async deleteAdvertisementByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get advertisement by IsActive index
   * This function gets data by index.
   */
  async getAdvertisementByIsActive(
    is_active: boolean,
  ): Promise<AdvertisementModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) advertisement by IsActive index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdvertisementByIsActive(
    is_active: boolean,
    data: AdvertisementModel
  ): Promise<AdvertisementModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const values = AdvertisementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete advertisement by IsActive index
   */
  async deleteAdvertisementByIsActive(
    is_active: boolean
  ): Promise<void> {
    const index = createIndexIsActive(
      is_active
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get advertisement by IsActivePosition index
   * This function gets data by index.
   */
  async getAdvertisementByIsActivePosition(
    is_active: boolean,
    position: number,
  ): Promise<AdvertisementModel[]> {
    const index = createIndexIsActivePosition(
      is_active,
      position
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) advertisement by IsActivePosition index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdvertisementByIsActivePosition(
    is_active: boolean,
    position: number,
    data: AdvertisementModel
  ): Promise<AdvertisementModel[]> {
    const index = createIndexIsActivePosition(
      is_active,
      position
    );

    const values = AdvertisementModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete advertisement by IsActivePosition index
   */
  async deleteAdvertisementByIsActivePosition(
    is_active: boolean,
    position: number
  ): Promise<void> {
    const index = createIndexIsActivePosition(
      is_active,
      position
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AdvertisementModel data array
   */
  private resultToData(values: Data[]): AdvertisementModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AdvertisementModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AdvertisementModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AdvertisementModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AdvertisementModel => item !== null);
  }
}

/**
 * Convert AdvertisementModel data to Value array
 */
function AdvertisementModelToValues(data: AdvertisementModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'image_url', type: DataType.string, defaultValue: '' },
    { key: 'link_url', type: DataType.string, defaultValue: '' },
    { key: 'position', type: DataType.number, defaultValue: 0 },
    { key: 'is_active', type: DataType.boolean, defaultValue: false },
    { key: 'start_date', type: DataType.string, defaultValue: '' },
    { key: 'end_date', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AdvertisementModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AdvertisementModel data
 */
function AdvertisementModelFromValues(values: Value[]): AdvertisementModel {
  const data: Partial<AdvertisementModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'image_url':
        data.image_url = ParseValue(value, DataType.string) as string;
        break;
      case 'link_url':
        data.link_url = ParseValue(value, DataType.string) as string;
        break;
      case 'position':
        data.position = ParseValue(value, DataType.number) as number;
        break;
      case 'is_active':
        data.is_active = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'start_date':
        data.start_date = ParseValue(value, DataType.string) as string;
        break;
      case 'end_date':
        data.end_date = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as AdvertisementModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for IsActive fields
 */
function createIndexIsActive(
  is_active: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_active, 'is_active'),
  ];

  return {
    fields: ['is_active'],
    values
  };
}
/**
 * Create index for IsActivePosition fields
 */
function createIndexIsActivePosition(
  is_active: boolean,
  position: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_active, 'is_active'),
    CreateValue(DataType.number, position, 'position'),
  ];

  return {
    fields: ['is_active', 'position'],
    values
  };
}

export default AdvertisementORM;